//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `StreamServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package StreamServer;

public class Song implements Cloneable,
                             java.io.Serializable
{
    public String titre;

    public String artiste;

    public String album;

    public String pathToFile;

    public Song()
    {
        this.titre = "";
        this.artiste = "";
        this.album = "";
        this.pathToFile = "";
    }

    public Song(String titre, String artiste, String album, String pathToFile)
    {
        this.titre = titre;
        this.artiste = artiste;
        this.album = album;
        this.pathToFile = pathToFile;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Song r = null;
        if(rhs instanceof Song)
        {
            r = (Song)rhs;
        }

        if(r != null)
        {
            if(this.titre != r.titre)
            {
                if(this.titre == null || r.titre == null || !this.titre.equals(r.titre))
                {
                    return false;
                }
            }
            if(this.artiste != r.artiste)
            {
                if(this.artiste == null || r.artiste == null || !this.artiste.equals(r.artiste))
                {
                    return false;
                }
            }
            if(this.album != r.album)
            {
                if(this.album == null || r.album == null || !this.album.equals(r.album))
                {
                    return false;
                }
            }
            if(this.pathToFile != r.pathToFile)
            {
                if(this.pathToFile == null || r.pathToFile == null || !this.pathToFile.equals(r.pathToFile))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::StreamServer::Song");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, titre);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, artiste);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, album);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, pathToFile);
        return h_;
    }

    public Song clone()
    {
        Song c = null;
        try
        {
            c = (Song)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.titre);
        ostr.writeString(this.artiste);
        ostr.writeString(this.album);
        ostr.writeString(this.pathToFile);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.titre = istr.readString();
        this.artiste = istr.readString();
        this.album = istr.readString();
        this.pathToFile = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Song v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Song ice_read(com.zeroc.Ice.InputStream istr)
    {
        Song v = new Song();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Song> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Song v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Song> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Song.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Song _nullMarshalValue = new Song();

    /** @hidden */
    public static final long serialVersionUID = 1534477810L;
}
