//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `StreamServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package StreamServer;

public interface StreamingPrx extends com.zeroc.Ice.ObjectPrx
{
    default Song[] getSongList()
    {
        return getSongList(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Song[] getSongList(java.util.Map<String, String> context)
    {
        return _iceI_getSongListAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Song[]> getSongListAsync()
    {
        return _iceI_getSongListAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Song[]> getSongListAsync(java.util.Map<String, String> context)
    {
        return _iceI_getSongListAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Song[]> _iceI_getSongListAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Song[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getSongList", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     Song[] ret;
                     ret = songListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default Song searchSong(String s)
    {
        return searchSong(s, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Song searchSong(String s, java.util.Map<String, String> context)
    {
        return _iceI_searchSongAsync(s, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Song> searchSongAsync(String s)
    {
        return _iceI_searchSongAsync(s, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Song> searchSongAsync(String s, java.util.Map<String, String> context)
    {
        return _iceI_searchSongAsync(s, context, false);
    }

    /**
     * @hidden
     * @param iceP_s -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Song> _iceI_searchSongAsync(String iceP_s, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Song> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "searchSong", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_s);
                 }, istr -> {
                     Song ret;
                     ret = Song.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void addSong(Song s)
    {
        addSong(s, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void addSong(Song s, java.util.Map<String, String> context)
    {
        _iceI_addSongAsync(s, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> addSongAsync(Song s)
    {
        return _iceI_addSongAsync(s, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> addSongAsync(Song s, java.util.Map<String, String> context)
    {
        return _iceI_addSongAsync(s, context, false);
    }

    /**
     * @hidden
     * @param iceP_s -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_addSongAsync(Song iceP_s, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "addSong", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     Song.ice_write(ostr, iceP_s);
                 }, null);
        return f;
    }

    default void updateSong(Song s)
    {
        updateSong(s, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void updateSong(Song s, java.util.Map<String, String> context)
    {
        _iceI_updateSongAsync(s, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> updateSongAsync(Song s)
    {
        return _iceI_updateSongAsync(s, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> updateSongAsync(Song s, java.util.Map<String, String> context)
    {
        return _iceI_updateSongAsync(s, context, false);
    }

    /**
     * @hidden
     * @param iceP_s -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_updateSongAsync(Song iceP_s, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "updateSong", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     Song.ice_write(ostr, iceP_s);
                 }, null);
        return f;
    }

    default String deleteSong(Song s)
    {
        return deleteSong(s, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String deleteSong(Song s, java.util.Map<String, String> context)
    {
        return _iceI_deleteSongAsync(s, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String> deleteSongAsync(Song s)
    {
        return _iceI_deleteSongAsync(s, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String> deleteSongAsync(Song s, java.util.Map<String, String> context)
    {
        return _iceI_deleteSongAsync(s, context, false);
    }

    /**
     * @hidden
     * @param iceP_s -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String> _iceI_deleteSongAsync(Song iceP_s, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "deleteSong", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     Song.ice_write(ostr, iceP_s);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default void startStream(Song s)
    {
        startStream(s, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void startStream(Song s, java.util.Map<String, String> context)
    {
        _iceI_startStreamAsync(s, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> startStreamAsync(Song s)
    {
        return _iceI_startStreamAsync(s, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> startStreamAsync(Song s, java.util.Map<String, String> context)
    {
        return _iceI_startStreamAsync(s, context, false);
    }

    /**
     * @hidden
     * @param iceP_s -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_startStreamAsync(Song iceP_s, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "startStream", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     Song.ice_write(ostr, iceP_s);
                 }, null);
        return f;
    }

    default void pauseStream()
    {
        pauseStream(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void pauseStream(java.util.Map<String, String> context)
    {
        _iceI_pauseStreamAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> pauseStreamAsync()
    {
        return _iceI_pauseStreamAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> pauseStreamAsync(java.util.Map<String, String> context)
    {
        return _iceI_pauseStreamAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_pauseStreamAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "pauseStream", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default void stopStream()
    {
        stopStream(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void stopStream(java.util.Map<String, String> context)
    {
        _iceI_stopStreamAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> stopStreamAsync()
    {
        return _iceI_stopStreamAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> stopStreamAsync(java.util.Map<String, String> context)
    {
        return _iceI_stopStreamAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_stopStreamAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "stopStream", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static StreamingPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), StreamingPrx.class, _StreamingPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static StreamingPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), StreamingPrx.class, _StreamingPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static StreamingPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), StreamingPrx.class, _StreamingPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static StreamingPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), StreamingPrx.class, _StreamingPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static StreamingPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, StreamingPrx.class, _StreamingPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static StreamingPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, StreamingPrx.class, _StreamingPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default StreamingPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (StreamingPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default StreamingPrx ice_adapterId(String newAdapterId)
    {
        return (StreamingPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default StreamingPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (StreamingPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default StreamingPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (StreamingPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default StreamingPrx ice_invocationTimeout(int newTimeout)
    {
        return (StreamingPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default StreamingPrx ice_connectionCached(boolean newCache)
    {
        return (StreamingPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default StreamingPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (StreamingPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default StreamingPrx ice_secure(boolean b)
    {
        return (StreamingPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default StreamingPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (StreamingPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default StreamingPrx ice_preferSecure(boolean b)
    {
        return (StreamingPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default StreamingPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (StreamingPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default StreamingPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (StreamingPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default StreamingPrx ice_collocationOptimized(boolean b)
    {
        return (StreamingPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default StreamingPrx ice_twoway()
    {
        return (StreamingPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default StreamingPrx ice_oneway()
    {
        return (StreamingPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default StreamingPrx ice_batchOneway()
    {
        return (StreamingPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default StreamingPrx ice_datagram()
    {
        return (StreamingPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default StreamingPrx ice_batchDatagram()
    {
        return (StreamingPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default StreamingPrx ice_compress(boolean co)
    {
        return (StreamingPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default StreamingPrx ice_timeout(int t)
    {
        return (StreamingPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default StreamingPrx ice_connectionId(String connectionId)
    {
        return (StreamingPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default StreamingPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (StreamingPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::StreamServer::Streaming";
    }
}
